openapi: 3.0.3
info:
  title: 'Reverse Geocoding API'
  description: 'This is a simple reverse geocoding API that can use for translate geo coordinates to address.'
  version: 0.0.1
servers:
  - url: https://mreversegeocoder.gsi.go.jp
paths:
  /reverse-geocoder/LonLatToAddress:
    get:
      tags:
        - ReverseGeocoding
      summary: 'Gets the address from geo coordinates.'
      parameters:
        -
          name: lat
          in: query
          description: Latitude
          schema:
            type: number
          example: 34.6878443488889
        -
          name: lon
          in: query
          description: Longitude
          schema:
            type: number
          example: 135.534442886667
      responses:
        200:
          description: 'Address info'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Results'
        400:
          description: 'Error message.'
          content:
            application/json:
              schema:
                type: string
components:
  schemas:
    Results:
      type: "object"
      properties: 
        results:
          type: object
          properties: 
            muniCd: 
              type: string
              description: Address Code
              example: 27128
            lv01Nm: 
              type: string
              description: Address
              example: 大阪城
